module.exports = [
  'Greetings and salutations! :dancing_cat:',
  'Hey! :dabcat:',
  'Morning :sleepy_cat:',
  'Good morning :meow_coffee:',
  'Nice to see you again :cat_with_milk:',
  'Have a productive day! :cat_typing:',
  'Have a good day :nyan_parrot:',
  'Glad to see you :meow_wow:',
  'Hello! :waiting_cat:',
  'I\'ve been looking for you :cat_with_loupe:',
  'Let\'s work :compcat:',
  'Nice to meet you! :cat_loves_you:',
  'High five :cat_high_five2:',
  'I missed you :meow_cookie:',
  'Meow :meow:',
  'Hi, human! :cool_cat2:',
  'Hi, how are you? :cute_cat:',
  'Ciao! :ciao_cat:',
]
